#model definition parameters
hidden_dimension: 200
input_channels: 3
sequence_length: 10
context_length: 5
temporal_conv_feature_factor: 1
bezier_order: 7
use_float: False

#training hyperparameters
gpu: 0
batch_size: 128
learning_rate: 1.0E-4
momentum: 1.0E-1
nesterov: False
dampening: 0.01E-0
loss_weights: [0.1, 1.0, 0.1]
num_epochs: 100
num_workers: 0
loss_reduction: "mean"

#debugging settings
debug: False