#model definition parameters
use_float: False
input_channels: 3

#training hyperparameters
gpu: 0
batch_size: 128
learning_rate: 1.0E-3
momentum: 1.0E-3
num_epochs: 100
num_workers: 0
control_loss_reduction: "sum"

#debugging settings
debug: False