#model definition parameters
input_channels: 3
output_dimension: 2

#training hyperparameters
gpu: 0
batch_size: 96
learning_rate: 1.0E-3
momentum: 1.0E-4
num_epochs: 500
num_workers: 0
loss_function: "MSE"
loss_reduction: "mean"
nesterov: False