#model definition parameters
hidden_dimension: 200
input_channels: 3
sequence_length: 60
context_length: 5
temporal_conv_feature_factor: 1
use_float: False

#training hyperparameters
gpu: 1
batch_size: 96
learning_rate: 5.0E-4
momentum: 1.0E-3
loss_weights: [1.0, 1.0]
num_epochs: 100
num_workers: 0
position_loss_reduction: "mean"
downsample_method: "spline"

#debugging settings
debug: False