#datasets definition
datasets:
  -
    image_db: D:\f1_training_data\multiplayer_australia_test_3\images\image_lmdb
    label_db: D:\f1_training_data\multiplayer_australia_test_3\images\pose_sequence_label_lmdb
    key_file: D:\f1_training_data\multiplayer_australia_test_3\goodkeys.txt
image_size: [66, 200]

#model definition parameters
hidden_dimension: 100
input_channels: 3
sequence_length: 15
context_length: 5
temporal_conv_feature_factor: 1
use_float: False
learnable_initial_state: True

#training hyperparameters
gpu: 0
batch_size: 64
learning_rate: 1.0E-6
momentum: 1.0E-4
loss_weights: [1.0, 0.0]
num_epochs: 100
num_workers: 0
position_loss_reduction: "sum"

#debugging settings
debug: False