batch_size: 16
context_length: 10
dataset_dir: D:\test_data\toy_dataset\images\pose_sequence_labels
gpu: 0
hidden_dimension: 100
image_directory: D:\test_data\toy_dataset\images_66_200
image_size:
- 66
- 200
input_channels: 3
learning_rate: 0.001
loss_weights:
- 1.0
- 1.0
momentum: 0.0
num_epochs: 10
num_workers: 0
output_directory: model_out
sequence_length: 7
temporal_conv_feature_factor: 1
