pure_pursuit_control:
    ros__parameters:
        #model_file : 'D:/f1_model_files/bezier_predictor/with_geometric_variants/cleansplinedata_comet/bezier_predictor_no_optflow_no_vel_loss_no_param_loss/epoch_100_params.pt'
        #model_file : 'D:/f1_model_files/fix_first_point/comet_pulls/194edccacc6443849188dac400a3ab0c/epoch_100_params.pt' #fix first point, with 3d conv

        ### Canada with Multiplayer Models ###
        #model_file : 'D:/f1_model_files/canada/08a2be9466c0484dba9bbe37d6fd7a76/epoch_135_params.pt' #
        #model_file : 'D:/f1_model_files/canada/08a2be9466c0484dba9bbe37d6fd7a76/epoch_200_params.pt' #
        #model_file : 'D:/f1_model_files/canada/08a2be9466c0484dba9bbe37d6fd7a76/epoch_135_params.pt' #
        #model_file : 'D:/f1_model_files/canada/07cc9290994b4316909c834c13cda45f/epoch_100_params.pt' #
        #model_file : 'D:/f1_model_files/canada/07cc9290994b4316909c834c13cda45f/epoch_110_params.pt' #
        #model_file : 'D:/f1_model_files/canada/07cc9290994b4316909c834c13cda45f/epoch_200_params.pt'

        ### End Canada with Multiplayer Models ###
        ### Canada Raceline Prediction ###
        #model_file : 'D:/f1_model_files/raceline_predictor/068981ebdf9b48e8b7f10456cd19ec76/epoch_150_params.pt'
        #model_file : 'D:/f1_model_files/raceline_predictor/2aaa0a45b6f14dc9bdbecb91bc794c54/epoch_200_params.pt'
        #model_file : 'D:/f1_model_files/raceline_predictor/068981ebdf9b48e8b7f10456cd19ec76/epoch_150_params.pt'
        model_file : 'D:/f1_model_files/raceline_predictor/068981ebdf9b48e8b7f10456cd19ec76/epoch_200_params.pt'

        ### End Canada Raceline Prediction ###



        #model_file : 'D:/f1_model_files/bezier_predictor/noconv3d/8a67bea64eea44efa0024ad13ca70fb6/epoch_100_params.pt' #no 3d convolution, slow learning rate
        #model_file : 'D:/f1_model_files/bezier_predictor/noconv3d/0fc8be197bf94dcfb99d491e74d6ece3/epoch_100_params.pt' #no 3d convolution, fast learning rate
        #model_file : 'D:/f1_model_files/cometpulls/bezier/38ad4466dc84463bbba04d3132e9a2ad_from_comet/epoch_100_params.pt' #only australia data
        #model_file : 'D:/f1_model_files/cometpulls/bezier/74740994ece64bd19e4d5ca59422dfcd_from_comet/epoch_100_params.pt' #combined with silverstone data
        #model_file : 'D:/f1_model_files/cometpulls/bezier/6f4eace2f1674bd585d921815599cc70_from_comet/epoch_66_params.pt' #combined with silverstone data
        #model_file : 'D:/f1_model_files/cometpulls/bezier/7bc671d6548743be9555cf0136601094_from_comet/epoch_100_params.pt' #combined with silverstone data
        #model_file : 'D:/f1_model_files/cometpulls/bezier/c817b91309f94776a83417788d9e5963_from_comet/epoch_60_params.pt' #combined with silverstone data, bezier order 3
        #model_file : 'D:/f1_model_files/cometpulls/bezier/75a14399a3e1422d853b298af614635e_from_comet/epoch_77_params.pt' #combined with silverstone data, bezier order 3
        #model_file : 'D:/f1_model_files/cometpulls/bezier/1bb363d3c94f4224a3c08757b2f756de_from_comet/epoch_80_params.pt' #combined with silverstone data, bezier order 3, better loss
        #model_file : 'D:/f1_model_files/cometpulls/bezier/cba533f5861948ee826109d2ec8344fe_from_comet/epoch_77_params.pt' #combined with silverstone data, bezier order 5
        #model_file : 'D:/f1_model_files/cometpulls/bezier/6165951b25844589857597596118dfce_from_comet/epoch_100_params.pt' #combined with silverstone data, bezier order 5
        #model_file : 'D:/f1_model_files/cometpulls/bezier/aa77cbe4b0eb4e63882bc0b7f0a4c44b_from_comet/epoch_100_params.pt' #combined with silverstone data, bezier order 5, better loss
        
        
        publish_all_cars: False
        use_compressed_images: True
        lookahead_gain : 0.6
        velocity_lookahead_gain: 0.15
        plot : True
        gpu : 0
        x_scale_factor : 1.0
        velocity_scale_factor: 1.0
        num_sample_points : 500
        left_steer_factor: 3.6
        right_steer_factor: 3.3
        max_speed: 85.0
        max_centripetal_acceleration: 15.0
