pure_pursuit_control:
    ros__parameters:
        model_file : 'D:/f1_model_files/bezier_predictor/with_geometric_variants/cleansplinedata_comet/bezier_predictor_no_optflow_no_vel_loss_no_param_loss/epoch_100_params.pt'
        lookahead_gain : 0.5
        cropwidth : 1758
        cropheight : 362
        plot : False
        gpu : 0
        x_scale_factor : 1.25