f1_image_publisher:
  ros__parameters:
    search_string : "F1"
    capture_frequency: 35.0
    resize_width: 0
    resize_height: 0
f1_data_publisher:
  ros__parameters:
    hostname : "127.0.0.1"
    port: 20777
    rebroadcast: False
    publish_all_cars: True