f1_image_publisher:
  ros__parameters:
    search_string : "F1"
    crop_width: 1758
    crop_height: 362
    resize_height: 66
    resize_width: 200
f1_data_publisher:
  ros__parameters:
    hostname : "127.0.0.1"
    port: 20777
    rebroadcast: True