pure_pursuit_control:
    ros__parameters:
        model_file : 'D:/f1_model_files/cometpulls/posepredictor/53ac4438361f4e72868b4b0e977b5c8c_from_comet/epoch_100_params.pt'
        use_compressed_images: True
        lookahead_gain : 0.5
        plot : True
        gpu : 0
        x_scale_factor : 1.00
        velocity_scale_factor: 1.0