pure_pursuit_control:
    ros__parameters:
        #model_file : 'D:/f1_model_files/cometpulls/posepredictor/53ac4438361f4e72868b4b0e977b5c8c_from_comet/epoch_100_params.pt'
        model_file : 'D:/f1_model_files/pose_predictor/ee556ae3f7ee4e73888b9f8bdf36497f/epoch_100_params.pt' #no 3d convolution
        use_compressed_images: True
        lookahead_gain : 0.5
        plot : True
        gpu : 0
        x_scale_factor : 1.20
        velocity_scale_factor: 1.0