#datasets definition
datasets:
  -
    image_db: /p/DeepRacing/datasets/multiplayer_captures/australia_multiplayer_good/images/image_lmdb
    opt_flow_db: /p/DeepRacing/datasets/multiplayer_captures/australia_multiplayer_good/images/optical_flow_lmdb
    label_db: /p/DeepRacing/datasets/multiplayer_captures/australia_multiplayer_good/images/pose_sequence_labels_lmdb
    key_file: /p/DeepRacing/datasets/multiplayer_captures/australia_multiplayer_good/goodkeys.txt
  -
    image_db: /p/DeepRacing/datasets/multiplayer_captures/australia_multiplayer_also_good/images/image_lmdb
    opt_flow_db: /p/DeepRacing/datasets/multiplayer_captures/australia_multiplayer_also_good/images/optical_flow_lmdb
    label_db: /p/DeepRacing/datasets/multiplayer_captures/australia_multiplayer_also_good/images/pose_sequence_labels_lmdb
    key_file: /p/DeepRacing/datasets/multiplayer_captures/australia_multiplayer_also_good/goodkeys.txt
  -
    image_db: /p/DeepRacing/datasets/multiplayer_captures/australia_more_more_yet_again/images/image_lmdb
    opt_flow_db: /p/DeepRacing/datasets/multiplayer_captures/australia_more_more_yet_again/images/optical_flow_lmdb
    label_db: /p/DeepRacing/datasets/multiplayer_captures/australia_more_more_yet_again/images/pose_sequence_labels_lmdb
    key_file: /p/DeepRacing/datasets/multiplayer_captures/australia_more_more_yet_again/goodkeys.txt
  -
    image_db: /p/DeepRacing/datasets/multiplayer_captures/australia_more_yet_again/images/image_lmdb
    opt_flow_db: /p/DeepRacing/datasets/multiplayer_captures/australia_more_yet_again/images/optical_flow_lmdb
    label_db: /p/DeepRacing/datasets/multiplayer_captures/australia_more_yet_again/images/pose_sequence_labels_lmdb
    key_file: /p/DeepRacing/datasets/multiplayer_captures/australia_more_yet_again/goodkeys.txt
  -
    image_db: /p/DeepRacing/datasets/multiplayer_captures/trent_lazy_lap/images/image_lmdb
    opt_flow_db: /p/DeepRacing/datasets/multiplayer_captures/trent_lazy_lap/images/optical_flow_lmdb
    label_db: /p/DeepRacing/datasets/multiplayer_captures/trent_lazy_lap/images/pose_sequence_labels_lmdb
    key_file: /p/DeepRacing/datasets/multiplayer_captures/trent_lazy_lap/goodkeys.txt
image_size: [66, 200]

#model definition parameters
hidden_dimension: 200
input_channels: 3
sequence_length: 10
context_length: 5
temporal_conv_feature_factor: 1
use_float: False

#training hyperparameters
gpu: 1
batch_size: 64
learning_rate: 5.0E-4
momentum: 1.0E-3
loss_weights: [1.0, 1.0]
num_epochs: 100
num_workers: 0
position_loss_reduction: "mean"
downsample_method: "spline"

#debugging settings
debug: False