search_string: "F1"
driver_name: "Trent"
images_folder: "images"
udp_folder: "udp_data"
udp_threads: 3
udp_port: 20777
image_threads: 3
image_capture_frequency: 45.0
initial_delay_time: 3.0
image_extension: "jpg"
use_json: True
spectating: True
init_paused: True