search_string: "F1"
driver_name: "Trent"
images_folder: "images"
udp_folder: "udp_data"
udp_thread_sleeptime: 75
udp_port: 20777
image_threads: 2
image_capture_frequency: 35.0
initial_delay_time: 3.0
image_extension: "jpg"
log_images: True
use_json: True
spectating: True
init_paused: False
udp_threads:
  motion: 2
  session: 1
  lap_data: 2
  event: 0
  participants: 1 
  car_setups: 1
  telemetry: 2 
  car_status:  2
