#datasets definition
datasets:
  -
    image_db: D:\f1_training_data\australia_multiplayer_also_good\images\image_lmdb
    opt_flow_db: D:\f1_training_data\australia_multiplayer_also_good\images\optical_flow_lmdb
    label_db: D:\f1_training_data\australia_multiplayer_also_good\images\pose_sequence_label_lmdb
    key_file: D:\f1_training_data\australia_multiplayer_also_good\goodkeys.txt
  -
    image_db: D:\f1_training_data\australia_multiplayer_good\images\image_lmdb
    opt_flow_db: D:\f1_training_data\australia_multiplayer_good\images\optical_flow_lmdb
    label_db: D:\f1_training_data\australia_multiplayer_good\images\pose_sequence_label_lmdb
    key_file: D:\f1_training_data\australia_multiplayer_good\goodkeys.txt
image_size: [66, 200]

#model definition parameters
hidden_dimension: 100
input_channels: 5
sequence_length: 20
context_length: 5
temporal_conv_feature_factor: 1
use_float: False

#training hyperparameters
gpu: 0
batch_size: 64
learning_rate: 1.0E-6
momentum: 1.0E-4
loss_weights: [0.5, 1.5]
num_epochs: 100
num_workers: 0
position_loss_reduction: "sum"

#debugging settings
debug: False