#dataset definition
label_db: D:\f1_training_data\abu_dhabi_multiplayer\images\pose_sequence_label_lmdb
image_db: D:\f1_training_data\abu_dhabi_multiplayer\images\image_lmdb
opt_flow_db: D:\f1_training_data\abu_dhabi_multiplayer\images\optical_flow_lmdb
key_file: D:\f1_training_data\abu_dhabi_multiplayer\dbkeys.txt
image_size: [66, 200]

#model definition parameters
hidden_dimension: 100
input_channels: 3
sequence_length: 25
context_length: 5
temporal_conv_feature_factor: 1
use_float: False

#training hyperparameters
gpu: 0
batch_size: 64
learning_rate: 1.0E-5
momentum: 0.0
loss_weights: [0.5, 1.5]
num_epochs: 100
num_workers: 0
position_loss_reduction: "sum"

#debugging settings
debug: False