#datasets definition
datasets:
  -
    image_db: D:\f1_training_data\australia_multiplayer_also_good\images\image_lmdb
    label_db: D:\f1_training_data\australia_multiplayer_also_good\images\pose_sequence_label_lmdb
    key_file: D:\f1_training_data\australia_multiplayer_also_good\goodkeys.txt
  -
    image_db: D:\f1_training_data\australia_multiplayer_good\images\image_lmdb
    label_db: D:\f1_training_data\australia_multiplayer_good\images\pose_sequence_label_lmdb
    key_file: D:\f1_training_data\australia_multiplayer_good\goodkeys.txt
  -
    image_db: D:\f1_training_data\australia_more_more_yet_again\images\image_lmdb
    label_db: D:\f1_training_data\australia_more_more_yet_again\images\pose_sequence_label_lmdb
    key_file: D:\f1_training_data\australia_more_more_yet_again\goodkeys.txt
  -
    image_db: D:\f1_training_data\australia_more_yet_again\images\image_lmdb
    label_db: D:\f1_training_data\australia_more_yet_again\images\pose_sequence_label_lmdb
    key_file: D:\f1_training_data\australia_more_yet_again\goodkeys.txt
  -
    image_db: D:\f1_training_data\trent_lazy_lap\images\image_lmdb
    label_db: D:\f1_training_data\trent_lazy_lap\images\pose_sequence_label_lmdb
    key_file: D:\f1_training_data\trent_lazy_lap\goodkeys.txt
image_size: [66, 200]

#model definition parameters
hidden_dimension: 200
input_channels: 3
sequence_length: 12
context_length: 5
temporal_conv_feature_factor: 1
use_float: False

#training hyperparameters
gpu: 1
batch_size: 64
learning_rate: 1.0E-4
momentum: 1.0E-3
loss_weights: [1.0, 0.25, 0.25, 0.25, 0.1, 0.1]
num_epochs: 100
num_workers: 0
position_loss_reduction: "mean"

#debugging settings
debug: False