{
  data:
  {
    dirs: [
      /p/DeepRacing/unpacked_datasets/local_fitting/v1/deepracing_standard/
    ]
  },
  trainer:
  {
      optimizer : Adam,
      learning_rate: 5E-4,
      momentum: 0.0,
      nesterov: False,
      betas: [0.99, 0.9999], 
      eps: 1E-8,
      weight_decay: 0.0,
      epochs: 200,
      batch_size: 512,
      ade_loss : False,
      float32: True,
  }
}