{
    comet:
    {
        tags: ["filtered_v2_data", "trained_on_lambda", "old_loss"]
    },
    data:
    {
        dir: /p/DeepRacing/unpacked_datasets/aligned_to_ego/v2/deepracing_standard
    },
    trainer:
    {
        optimizer : Adam,
        learning_rate: 5E-4,
        momentum: 0.0,
        nesterov: False,
        gpu_index: 0,
        betas: [0.99, 0.9999], 
        eps: 1E-8,
        weight_decay: 0.0,
        epochs: 200,
        batch_size: 256,
        kbezier: 7,
        ade_loss : False
    },
    net:
    {
        input_dimension: 2,
        input_embedding:
        {
            velocity : True,
            quaternion : True,
            heading_angle : False,
            hidden_layers : [
                128,
                256,
                512,
                512
            ]
        },
        separate_boundary_embedder: True,
        boundary_embedding:
        {
            tangent : True,
            hidden_layers : [
                128,
                256,
                256,
                256
            ]
        },

        encoder: {
            in_size: 256,    
            hidden_size: 512
        },
        mixer_linear_stack: {
            hidden_sizes: [
                256,
                256,
                256,
                256,
                256
            ],
            out_size: 4
        },
        acc_decoder: {
            hidden_size: 512,
            in_size: 256,    
            num_acc_sections: 60,
            max_acc: 90.0,
            kbeziervel : 1,
            embedder_layers: [
                256,
                256,
                256,
                256
            ],
            output_layers : [
                512,
                512,
                512,
                512
            ],
            final_layer_tanh : False,
        }
    }
}