{
    # comet:
    # {
    #     tags: []
    # },
    data:
    {
        dir: /p/DeepRacing/unpacked_datasets/v4/online_multiplayer
    },
    trainer:
    {
        optimizer : Adam,
        learning_rate: 5E-4,
        momentum: 1E-6,
        nesterov: True,
        gpu_index: 0,
        betas: [0.99, 0.9999], 
        eps: 1E-8,
        weight_decay: 0.0,
        epochs: 200,
        batch_size: 32
    },
    net:
    {
        kbezier : 4,
        d_model : 64
    }
}