{
    data:
    {
        dir: /p/DeepRacing/unpacked_datasets/online_multiplayer/deepracing_standard
    },
    trainer:
    {
        optimizer : Adam,
        learning_rate: 1E-5,
        momentum: 0.0,
        nesterov: False,
        gpu_index: 0,
        betas: [0.99, 0.9999], 
        eps: 1E-8,
        weight_decay: 0.0,
        epochs: 500,
        batch_size: 256,
        kbezier: 4
    },
    net:
    {
        encoder: {
            in_size: 16,
            hidden_size: 32
        },
        mixer_linear_stack: {
            hidden_sizes: [
                256,
                256,
                32
            ],
            out_size: 4
        },
        init_vel_linear_stack: {
            hidden_sizes: [
                32
            ],
            out_size: 1,
            max_vel: 100.0
        },
        acc_decoder: {
            in_size: 16,
            hidden_size: 32,
            num_acc_sections: 10,
            max_acc: 100.0
        }
    }
}