{
    comet:
    {
        tags: ["filtered_v2_data"]
    },
    data:
    {
        dir: /p/DeepRacing/unpacked_datasets/filtered/v2/numpy_format
    },
    trainer:
    {
        optimizer : Adam,
        learning_rate: 2E-5,
        momentum: 0.0,
        nesterov: False,
        gpu_index: 0,
        betas: [0.99, 0.9999], 
        eps: 1E-8,
        weight_decay: 0.0,
        epochs: 500,
        batch_size: 64,
        kbezier: 7
    },
    net:
    {
        input_dimension : 2,
        final_layer_tanh : False,
        with_velocity_input : False,
        encoder: {
            in_size: 16,
            hidden_size: 32
        },
        mixer_linear_stack: {
            hidden_sizes: [
                256,
                256,
                32
            ],
            out_size: 4
        },

        acc_decoder: {
            in_size: 16,
            hidden_size: 32,
            num_acc_sections: 5,
            max_acc: 100.0
        }
    }
}