#model definition parameters
use_float: False
input_channels: 3

#training hyperparameters
gpu: 0
batch_size: 100
learning_rate: 5.0E-4
momentum: 1.0E-4
num_epochs: 100
num_workers: 0
control_loss_reduction: "mean"

#debugging settings
debug: False